name = "uscfvl"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

#[[kv_namespaces]]
#binding = "KV"			#KV绑定名默认不可修改

#id = "12eea38201bf486a985b04deabf217eb"				#KV数据库id
